image: berenger/specxci

specx:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DUSE_ADVANCE_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    
    
specx-debug:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DCMAKE_BUILD_TYPE=DEBUG -DUSE_ADVANCE_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test

specx-clang:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=clang++ cmake -DUSE_ADVANCE_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    
    
specx-debug-clang:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=clang++ cmake -DCMAKE_BUILD_TYPE=DEBUG -DUSE_ADVANCE_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test


specx-debug-coverage:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++ cmake -DCMAKE_BUILD_TYPE=DEBUG -DSPECX_USE_COVERAGE=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    - /usr/local/bin/lcov --gcov-tool /usr/bin/gcov-8 --directory ./ -c -o coverage-rapport.info
    - /usr/local/bin/lcov --gcov-tool /usr/bin/gcov-8 --list coverage-rapport.info
    - /usr/local/bin/genhtml -o ../coverage -t "Coverage example" coverage-rapport.info
  artifacts:
    paths:
      - coverage/

pages:
  tags:
    - medium
  stage: deploy
  dependencies:
    - specx-debug-coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

