image: berenger/spetabaruci

spetabaru:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++-8 cmake -DUSE_ADVANCE_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    
    
spetabaru-debug:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++-8 cmake -DCMAKE_BUILD_TYPE=DEBUG -DUSE_ADVANCE_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test

spetabaru-clang:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=clang++-8 cmake -DUSE_ADVANCE_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    
    
spetabaru-debug-clang:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=clang++-8 cmake -DCMAKE_BUILD_TYPE=DEBUG -DUSE_ADVANCE_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test


spetabaru-debug-coverage:
  tags:
    - medium
  script:
    - mkdir build
    - cd build
    - VERBOSE=1 CXX=g++-8 cmake -DCMAKE_BUILD_TYPE=DEBUG -DSPETABARU_USE_COVERAGE=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    - /usr/local/bin/lcov --gcov-tool /usr/bin/gcov-8 --directory ./ -c -o coverage-rapport.info
    - /usr/local/bin/lcov --gcov-tool /usr/bin/gcov-8 --list coverage-rapport.info
    - /usr/local/bin/genhtml -o ../coverage -t "Coverage example" coverage-rapport.info
  artifacts:
    paths:
      - coverage/

pages:
  tags:
    - medium
  stage: deploy
  dependencies:
    - spetabaru-debug-coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

